### ISSUE TITLE
Toggle wrapping text in inlines

### ISSUE THREAD

**Issue by askvortsov1** [jahudka/mdarea#3]
If adding inlines to a selected block of code that is already wrapped in inlines, it will just keep adding more layers of inlines. Most of the time, I'm assuming that users would prefer to toggle the current wrapping characters as opposed to adding new ones. Perhaps this could be an option provided to the constructor?

**Comment by jahudka** [comment]
this is awesome and an obvious omission, thanks! I'd even go so far as to say this shouldn't even be an option, but just the default behaviour, what do you think?

**Comment by askvortsov1** [comment]
Hmm the one case where the previous behavior might be useful is for inserting triple backticks, but that's something that most people are accustomed to doing manually I feel. But yeah with that in mind, I'll adjust the PR to remove the option and just make it the default :+1:

**Comment by jahudka** [comment]
❤️ you're the best!

**Comment by jahudka** [comment]
I think the case of code blocks is really not that big of an issue - I'd say usually when you want something to be inside a code block you don't write the actual code first and then wrap it in the code block markup, usually it's the other way around, so it should be okay for most people.. Thanks a lot!
